# Generated by Django 4.2.6 on 2023-11-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tempforms',
            name='name_temp',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='test_api.nametemp'),
        ),
    ]
